inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/StringLiterals:
  Enabled: false
